"""Backward-compatible facade for the split CLI UI package."""

from zzm_agent.cli_support.ui.legacy import *
from zzm_agent.cli_support.ui import legacy as _legacy

PROMPT_COMPLETION_MENU_RESERVED_LINES = _legacy.PROMPT_COMPLETION_MENU_RESERVED_LINES
MAX_VISIBLE_REASONING_CHARS = _legacy.MAX_VISIBLE_REASONING_CHARS
_compact_reasoning_for_display = _legacy._compact_reasoning_for_display
_install_completion_menu_highlight_patch = _legacy._install_completion_menu_highlight_patch
_install_markdown_code_style_patch = _legacy._install_markdown_code_style_patch
_is_code_like_line = _legacy._is_code_like_line
_is_light_terminal_background = _legacy._is_light_terminal_background
_is_prefix_subsequence = _legacy._is_prefix_subsequence
_pin_completion_menu_position = _legacy._pin_completion_menu_position
_plain_terminal_reply = _legacy._plain_terminal_reply
_slash_command_matches = _legacy._slash_command_matches
_strip_reply_emoji = _legacy._strip_reply_emoji
_windows_console_background_color = _legacy._windows_console_background_color
